# EDITABLE
boundaries:
  north_south:
    lower: -5.0 #UNIT Metres
    upper: 5.0 #UNIT Metres
  east_west:
    lower: -5.0 #UNIT Metres
    upper: 5.0 #UNIT Metres
  altitude: # Negative values because positive is downwards
    lower: -2.0 #UNIT Metres
    upper: -5.0 #UNIT Metres
  yaw:
    lower: -180 #UNIT Degrees
    upper: 180 #UNIT Degrees
number_of_waypoints:
  lower: 2
  upper: 10
iterations: 2
duration_for_faults: [1, 5] #UNIT Seconds
duration_between_faults: [1, 5] #UNIT Seconds
time_to_fault_start: [1, 5] #UNIT Seconds
# SELECTIVELY EDITABLE VALUES BETWEEN #!--
sensors:
  #--------------------------------
  - module_name: "accelerometer"
    root: "SENS_ACCEL"
    record: True
    data_type: px4_msgs.msg/SensorAccel
    topic_name: "/fmu/out/sensor_accel"
    faults:
  #!--------------------------------
      - type: "gaussian_noise._NOISE"
        active: True                 # EDITABLE
        vals: [0.0, 0.1]              # EDITABLE | Standard deviation of a normal distribution. 
      - type: "bias_shift._SHIF"
        active: False                  # EDITABLE
        vals: [0.0, 0.0]             # EDITABLE | Percentage (written as decimal) of shift in actual value.
      - type: "bias_scale._SCAL"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE | Scalar multiplier to scale actual value.
      - type: "drift._DRIFT"
        active: False                  # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE | Percentage (written as percent) of increase w.r.t. to original value with each timestep.
  #!--------------------------------
  - module_name: "gyroscope"
    root: "SENS_GYRO"
    record: True
    data_type: px4_msgs.msg/SensorGyro
    topic_name: "/fmu/out/sensor_gyro"
    faults:
  #!--------------------------------
      - type: "gaussian_noise._NOISE"
        active: True                 # EDITABLE
        vals: [0.0, 0.1]              # EDITABLE 
      - type: "bias_shift._SHIF"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
      - type: "bias_scale._SCAL"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
      - type: "drift._DRIFT"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
  #!--------------------------------
  - module_name: "magnetometer"
    root: "SENS_MAG"
    record: True
    data_type: px4_msgs.msg/SensorMag
    topic_name: "/fmu/out/sensor_mag"
    faults:
  #!--------------------------------
      - type: "gaussian_noise._NOISE"
        active: True                 # EDITABLE
        vals: [0.0, 0.1]              # EDITABLE
      - type: "bias_shift._SHIF"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
      - type: "bias_scale._SCAL"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
      - type: "drift._DRIFT"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
  #!--------------------------------
  - module_name: "barometer"
    root: "SENS_BARO"
    record: True
    data_type: px4_msgs.msg/SensorBaro
    topic_name: "/fmu/out/sensor_baro"
    faults:
  #!--------------------------------
      - type: "gaussian_noise._NOISE"
        active: True                 # EDITABLE
        vals: [0.0, 0.1]              # EDITABLE
      - type: "bias_shift._SHIF"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
      - type: "bias_scale_SCAL"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
      - type: "drift._DRIFT"
        active: False                 # EDITABLE
        vals: [0.0, 0.0]              # EDITABLE
  #--------------------------------
