sensors:
  - label: "ACCEL"
    name: "accelerometer"
    type:
      - label: "NOISE"
        description: "noise_Gaussian_std_dev"
      - label: "SHIF"
        description: "shift_decimal_scalar"
      - label: "SCAL"
        description: "scaling_decimal_scalar"
      - label: "DRIFT"
        description: "drift_percent"
  - label: "GYRO"
    name: "gyroscope"
    type:
      - label: "NOISE"
        description: "noise_Gaussian_std_dev"
      - label: "SHIF"
        description: "shift_decimal_scalar"
      - label: "SCAL"
        description: "scaling_decimal_scalar"
      - label: "DRIFT"
        description: "drift_percent"
  - label: "MAG"
    name: "magnetometer"
    type:
      - label: "NOISE"
        description: "noise_Gaussian_std_dev"
      - label: "SHIF"
        description: "shift_decimal_scalar"
      - label: "SCAL"
        description: "scaling_decimal_scalar"
      - label: "DRIFT"
        description: "drift_percent"
  - label: "BARO"
    name: "barometer"
    type:
      - label: "NOISE"
        description: "noise_Gaussian_std_dev"
      - label: "SHIF"
        description: "shift_decimal_scalar"
      - label: "SCAL"
        description: "scaling_decimal_scalar"
      - label: "DRIFT"
        description: "drift_percent"
